### ISSUE TITLE
Built in support chat

### ISSUE THREAD

**Issue by larserikgk** [CasualGaming/studlan#118]
I have been thinking about an integrated messaging system that could be used for support during events like TrøndeLAN. Since we already have postman install, I don't think it would be a lot of work to implement some kind of messaging system where crew could respond to questions from users that are logged in. Any input @tordsk @Torrib ?

**Comment by Torrib** [comment]
Should probably think a step further to create something that can ease communication between teams and administrators during competitions as well.
Maybe some sort of chat rooms for the different competitions (restricted to the users that are signed up for the competition).

**Comment by larserikgk** [comment]
That is a good option, but then we will need to use another app than postman. I'm sure there are some open source chat apps that we can customize.

**Comment by melwil** [comment]
I can recommend using slack with smooch [1].

Slack is great because it is a chat anyone can connect to, from literally anything these days.
Smooch is great because you can have a chat window in the browser, which can be used by anonymous users. When a user starts an anonymous chat, a new channel is created on the slack, and a "dispatch channel" is notified. Any user can then join the channel and chat, which will not be sent to the user directly. Sending messages back to the user is done with commands like ´/sk_answer´ or similar. This way the staff can discuss solutions before answering, and it will all be neatly sorted in separate channels.

We use this for a game community today, and it has worked great. The threshold for talking to admins has been lowered to basically nothing, and it is easy for us to coordinate answers.

The slack can also be joined by regular slack users, and you can have discussions with larger groups here, which also works great to coordinate competitions and other info for team leaders.

[1] https://smooch.io/slack/

**Comment by larserikgk** [comment]
Smooch looks rather smooth, but I think we will lay this issue on ice for now since CaG might move communication to Discord instead of Slack.
